import UIKit

enum AppStrings {
    static let homeVsAway = "%@ vs %@"
    static let statusPrefix = "Status: "
    static let empty = ""
    static let dash = "-"
    static let fullTime = "FT"
    static let unknownCountry = "Unknown"
    static let liveMinuteSuffix = "'"
    static let timeFormat = "HH:mm"
    static let realMadrid = "Real Madrid"
    static let barcelona = "Barcelona"
    static let villareal = "Villareal"
    static let mallorca = "Mallorca"
    static let chelsea = "Chelsea"
    static let manCity = "Man City"
    static let liverpool = "Liverpool"
    static let arsenal = "Arsenal"
    static let manUtd = "Man Utd"
    static let newcastle = "Newcastle"
    static let football = "Football"
    static let basketball = "Basketball"
    static let amFootball = "Am. Football"
}
